import type { Employee } from './types';

/**
 * Mock employee data for development/testing
 * Replace this with actual API data in production
 */
export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    firstName: 'Alice',
    surname: 'Johnson',
    department: 'Engineering',
    office: 'Oslo',
    skills: ['React', 'TypeScript', 'Node.js', 'Docker'],
    age: 32,
    supervisor: '-',
  },
  {
    id: '2',
    name: 'Bob Smith',
    firstName: 'Bob',
    surname: 'Smith',
    department: 'Design',
    office: 'Stockholm',
    skills: ['Figma', 'UI/UX', 'Prototyping'],
    age: 28,
    supervisor: '-',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    firstName: 'Charlie',
    surname: 'Brown',
    department: 'Engineering',
    office: 'Oslo',
    skills: ['Python', 'Django', 'PostgreSQL', 'AWS'],
    age: 35,
    supervisor: '-',
  },
  {
    id: '4',
    name: 'Diana Prince',
    firstName: 'Diana',
    surname: 'Prince',
    department: 'Product',
    office: 'Copenhagen',
    skills: ['Product Strategy', 'Analytics', 'User Research'],
    age: 30,
    supervisor: '-',
  },
  {
    id: '5',
    name: 'Erik Hansen',
    firstName: 'Erik',
    surname: 'Hansen',
    department: 'Engineering',
    office: 'Stockholm',
    skills: ['React', 'TypeScript', 'GraphQL', 'Jest'],
    age: 26,
    supervisor: '-',
  },
  {
    id: '6',
    name: 'Frida Andersson',
    firstName: 'Frida',
    surname: 'Andersson',
    department: 'Design',
    office: 'Oslo',
    skills: ['Figma', 'Illustration', 'Brand Design'],
    age: 29,
    supervisor: '-',
  },
  {
    id: '7',
    name: 'Gunnar Olsen',
    firstName: 'Gunnar',
    surname: 'Olsen',
    department: 'Engineering',
    office: 'Copenhagen',
    skills: ['Go', 'Kubernetes', 'Microservices', 'gRPC'],
    age: 38,
    supervisor: '-',
  },
  {
    id: '8',
    name: 'Hanna Lindberg',
    firstName: 'Hanna',
    surname: 'Lindberg',
    department: 'Product',
    office: 'Stockholm',
    skills: ['Product Management', 'Data Analysis', 'Agile'],
    age: 31,
    supervisor: '-',
  },
];

